apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: {{ .Values.namespace }}
  labels:
    app: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: grpc
