{{- if .Values.healthCheckPolicy.enabled }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "online-boutique.labels" . | nindent 4 }}
spec:
  default:
    checkIntervalSec: {{ .Values.healthCheckPolicy.intervalSec }}
    timeoutSec: {{ .Values.healthCheckPolicy.timeoutSec }}
    healthyThreshold: {{ .Values.healthCheckPolicy.healthyThreshold }}
    unhealthyThreshold: {{ .Values.healthCheckPolicy.unhealthyThreshold }}
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.healthCheckPolicy.port }}
        requestPath: {{ .Values.healthCheckPolicy.path }}
  targetRef:
    group: ""
    kind: Service
    name: frontend
{{- end }}
